---
- name: FirewallD
  hosts: localhost
  connection: local
  tasks:
  - name: FirewallD rules
    firewalld:
      permanent: yes
      immediate: yes
      rich_rule: "{{ item }}"
      state: enabled
    with_items:
      - 'rule forward-port port=8080 protocol=tcp to-port=80 family=ipv4'